version: 2.1
orbs:
  node: circleci/node@5.1.0
  ruby: circleci/ruby@2.1.0
jobs:
  build-and-test:
    working_directory: ~/project
    docker:
      - image: cimg/node:18.18.0
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18.12'
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run yarn tests
      - run:
          name: Check types
          command: yarn exec vue-tsc
  semgrep:
    docker:
      - image: returntocorp/semgrep
    steps:
      - checkout
      - run:
          name: Check code against community-provided semgrep rules
          command: semgrep ci --config auto
  integration-tests:
    docker:
      - image: cimg/ruby:3.2.2-browsers
    parallelism: 1
    steps:
      - checkout
      - ruby/install-deps
      - node/install:
          install-yarn: true
          node-version: '18.12'
      - node/install-packages:
          pkg-manager: yarn
      - ruby/rspec-test
  dependency-check:
    docker:
      - image: cimg/base:2023.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: check dependencies
          command: docker run -e VET_COMMUNITY_MODE=true ghcr.io/safedep/vet:latest scan -s --lockfiles ~/project/yarn.lock --filter-suite ~/project/vet-filter.yml --filter-fail

workflows:
  test_my_app:
    jobs:
      - build-and-test
      - semgrep
      - integration-tests
      - dependency-check
