version: 2.1
orbs:
  node: circleci/node@7.1.0
  ruby: circleci/ruby@2.1.0
jobs:
  build-and-test:
    working_directory: ~/project
    docker:
      - image: cimg/node:23.11.0
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '23.11.0'
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run yarn tests
      - run:
          name: Check types
          command: yarn exec vue-tsc
  lint:
    working_directory: ~/project
    docker:
      - image: cimg/node:23.11.0
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '23.11.0'
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Lint
          command: yarn lint
  semgrep:
    docker:
      - image: returntocorp/semgrep
    steps:
      - checkout
      - run:
          name: Check code against community-provided semgrep rules
          command: semgrep ci --config auto
  integration-tests:
    docker:
      - image: cimg/ruby:3.2.2-browsers
    parallelism: 1
    steps:
      - checkout
      - ruby/install-deps
      - node/install:
          install-yarn: true
          node-version: '23.11.0'
      - node/install-packages:
          pkg-manager: yarn
      - ruby/rspec-test

  bearer:
    docker:
      - image: cimg/ruby:3.2
    environment:
      # Set to default branch of your repo
      DEFAULT_BRANCH: main
    steps:
      - checkout
      - run: curl -sfL https://raw.githubusercontent.com/Bearer/bearer/main/contrib/install.sh | sh -s -- -b /tmp
      - run: CURRENT_BRANCH=$CIRCLE_BRANCH SHA=$CIRCLE_SHA1 /tmp/bearer scan .

workflows:
  test_my_app:
    jobs:
      - build-and-test
      - lint
      - semgrep
      - integration-tests
      - bearer
